step_distributions:
- type: WeibullExp
  params:
  - 2.552871953946462
  - 0.9753942145976437
  prior: 0.0732124684301627
- type: Gaussian
  params:
  - 1.5829616696925568
  - 3.983292394309768
  prior: 0.9267875315698373
time: 0.6162252460017044
