step_distributions:
- type: Exponential
  params:
  - 3.1981684696293984
  prior: 0.5
- type: Gaussian
  params:
  - -4.746428758413189
  - 0.08864364051499352
  prior: 0.5
time: 0.011769791999995505
